version: "3.9"

services:
  mongo:
    image: mongo
    restart: always
    env_file: .env
    logging:
      driver: none
    ports:
      - 0:27017:27017
  fastapi:
    image: fastapi
    build: .
    env_file: 
      - .env
    volumes:
      - ./:/app
    ports:
      - 0:8080:80